-- Records every practice answer for a question. Correctness is evaluated by the backend.
create table if not exists question_answer_attempts (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    question_type varchar(20) not null,
    submitted_answer_json clob not null,
    correct boolean not null,
    session_id varchar(80),
    answered_at timestamp with time zone not null,
    constraint fk_answer_attempt_question
        foreign key (question_id) references pmp_questions(id) on delete cascade,
    constraint question_answer_attempts_type_check
        check (question_type in ('MCQ', 'MRQ', 'MATCHING'))
);

create index if not exists idx_answer_attempt_question
    on question_answer_attempts(question_id);

create index if not exists idx_answer_attempt_question_time
    on question_answer_attempts(question_id, answered_at desc);

create index if not exists idx_answer_attempt_correct
    on question_answer_attempts(correct);
